/**
 * Shapes shared by the crochet assistant's server route and its client UI.
 *
 * Nothing here is secret and nothing here queries anything: this module is
 * imported by client components. Server-only logic lives beside it in
 * `catalog.ts`, `throttle.ts` and `run.ts`.
 */

/**
 * A pattern's Meemi Art difficulty assessment, as the assistant may show it.
 *
 * Derived on the server by the Difficulty engine from the product's enabled
 * `ProductDifficulty` row — never estimated, never taken from a description,
 * never from the model.
 */
export type AssistantDifficulty = {
  /** "Beginner", "Intermediate", … */
  levelLabel: string;
  /** "7.3" — out of 10. */
  score: string;
  /** "About 2–3 hours". */
  estimatedTime: string;
  /** Labels from the controlled technique vocabulary. */
  techniques: string[];
};

/**
 * A product as the assistant may show it.
 *
 * Every field is public catalogue data read from the database at request
 * time — never from the model and never from the browser. Deliberately absent:
 * database ids, storage keys, file names, SKUs, Paddle ids and anything about
 * orders. Cards are keyed and linked by slug.
 */
export type AssistantProduct = {
  slug: string;
  name: string;
  categoryName: string;
  priceCents: number;
  compareAtCents: number | null;
  imageUrl: string | null;
  imageAlt: string;
  /** Only when the product has real published reviews; otherwise null. */
  ratingAvg: number | null;
  reviewCount: number;
  /** Only when the product has an enabled difficulty assessment; otherwise null. */
  difficulty: AssistantDifficulty | null;
};

export type AssistantRecommendation = {
  product: AssistantProduct;
  /** The model's one-line reason, length-capped by the server. */
  reason: string;
  /**
   * The verified facts behind the recommendation — "Beginner", "About 2–3
   * hours", "Within your $5.00 budget" — generated by the server's matching
   * engine from the criteria the customer stated.
   */
  reasons: string[];
  /** "best" or "also" when the customer stated criteria; null for a general selection. */
  rank: "best" | "also" | null;
};

/** A side-by-side comparison, every cell built by the server from catalogue data. */
export type AssistantComparison = {
  products: { slug: string; name: string }[];
  rows: { label: string; values: string[] }[];
};

export type ChatTurn = {
  role: "user" | "assistant";
  content: string;
};

export type AssistantReply =
  | {
      ok: true;
      message: string;
      recommendations: AssistantRecommendation[];
      followUpQuestion: string | null;
      quickReplies: string[];
      comparison: AssistantComparison | null;
    }
  | {
      ok: false;
      /** Customer-safe wording only — never a provider or stack message. */
      error: string;
      fallbackHref: string;
      retryAfterSeconds?: number;
    };

/**
 * Hard limits, enforced on the server and mirrored in the UI so the input
 * cannot hold more than the route will accept.
 */
export const ASSISTANT_LIMITS = {
  /** One customer message. */
  maxMessageChars: 500,
  /** An earlier assistant turn echoed back as history. */
  maxAssistantChars: 1200,
  /** Turns of history sent per request — the short context window. */
  maxTurns: 12,
  /** Product cards in one reply. */
  maxRecommendations: 4,
} as const;
